In [1]:
import pandas as pd 
import numpy as np
import re

In [2]:
# Read the CSV file into a DataFrame
amrFinder = pd.read_csv('filtered_ReferenceGeneCatalog.tsv', delimiter='\t')

In [3]:
resfinder = pd.read_csv('Resfinder_phenotypes.txt', delimiter='\t', keep_default_na=False, na_values='')
# Replace empty strings ('') with '-'
resfinder = resfinder.replace(np.nan, '-')

In [4]:
card = pd.read_csv('aro_index.tsv', delimiter='\t')

In [5]:
amrFinder.iloc[1:5,]

,allele,gene_family,whitelisted_taxa,product_name,scope,type,subtype,class,subclass,refseq_protein_accession,...,genbank_start,genbank_stop,refseq_strand,refseq_start,refseq_stop,pubmed_reference,blacklisted_taxa,synonyms,hierarchy_node,db_version
1,NaN,aac(2')-IIa,NaN,kasugamycin N-acetyltransferase AAC(2')-IIa,core,AMR,AMR,AMINOGLYCOSIDE,KASUGAMYCIN,WP_063839881.1,...,12439,13221,+,101.0,883.0,22660700,NaN,NaN,aac(2')-IIa,2026-05-15.1
2,NaN,aac(2')-IIb,NaN,kasugamycin N-acetyltransferase AAC(2')-IIb,core,AMR,AMR,AMINOGLYCOSIDE,KASUGAMYCIN,WP_071224044.1,...,1,723,+,1.0,723.0,27929110,NaN,NaN,aac(2')-IIb,2026-05-15.1
3,NaN,aac(2')-Ia,NaN,aminoglycoside N-acetyltransferase AAC(2')-Ia,core,AMR,AMR,AMINOGLYCOSIDE,GENTAMICIN/PLAZOMICIN/TOBRAMYCIN,WP_004918308.1,...,264,800,+,101.0,637.0,"8407825,40178262",NaN,NaN,aac(2')-Ia,2026-05-15.1
4,NaN,aac(2')-Ib,NaN,aminoglycoside N-acetyltransferase AAC(2')-Ib,core,AMR,AMR,AMINOGLYCOSIDE,GENTAMICIN/TOBRAMYCIN,WP_003881640.1,...,265,852,+,101.0,688.0,8891143,NaN,NaN,aac(2')-Ib,2026-05-15.1

In [6]:
amrFinder["Resistance Mechanism"]="-"
amrFinder["Notes"]="-"
amrFinder["Database"]="Reference Gene Catalog"
amrFinder["ID"]=amrFinder["genbank_protein_accession"]
amrFinder2=amrFinder.loc[:,["ID","gene_family","genbank_protein_accession",
                           "genbank_nucleotide_accession",
                            "class", "subclass", "pubmed_reference",
                           "product_name","Resistance Mechanism", "Database", "Notes"]]

In [7]:
amrFinder2

,ID,gene_family,genbank_protein_accession,genbank_nucleotide_accession,class,subclass,pubmed_reference,product_name,Resistance Mechanism,Database,Notes
0,CDI94966.1,aac(2')-I(A267),CDI94966.1,HG530068.1,AMINOGLYCOSIDE,GENTAMICIN/TOBRAMYCIN,NaN,aminoglycoside N-acetyltransferase AAC(2')-I(A...,-,Reference Gene Catalog,-
1,BAM16262.1,aac(2')-IIa,BAM16262.1,AB669090.1,AMINOGLYCOSIDE,KASUGAMYCIN,22660700,kasugamycin N-acetyltransferase AAC(2')-IIa,-,Reference Gene Catalog,-
2,APB03221.1,aac(2')-IIb,APB03221.1,KX531051.1,AMINOGLYCOSIDE,KASUGAMYCIN,27929110,kasugamycin N-acetyltransferase AAC(2')-IIb,-,Reference Gene Catalog,-
3,AAA03550.1,aac(2')-Ia,AAA03550.1,L06156.2,AMINOGLYCOSIDE,GENTAMICIN/PLAZOMICIN/TOBRAMYCIN,"8407825,40178262",aminoglycoside N-acetyltransferase AAC(2')-Ia,-,Reference Gene Catalog,-
4,AAC44793.1,aac(2')-Ib,AAC44793.1,U41471.1,AMINOGLYCOSIDE,GENTAMICIN/TOBRAMYCIN,8891143,aminoglycoside N-acetyltransferase AAC(2')-Ib,-,Reference Gene Catalog,-
...,...,...,...,...,...,...,...,...,...,...,...
8414,APB03225.1,vgbC,APB03225.1,KX531055.1,STREPTOGRAMIN,STREPTOGRAMIN,27929110,streptogramin B lyase Vgb(C),-,Reference Gene Catalog,-
8415,BAA19394.1,vmlR,BAA19394.1,AB001488.1,LINCOSAMIDE/PLEUROMUTILIN/STREPTOGRAMIN,LINCOMYCIN/TIAMULIN/VIRGINIAMYCIN M,30126986,ABC-F type ribosomal protection protein VmlR,-,Reference Gene Catalog,-
8416,CAA26235.1,vph,CAA26235.1,X02393.1,TUBERACTINOMYCIN,VIOMYCIN,2987648,viomycin phosphotransferase,-,Reference Gene Catalog,-
8417,BCK56342.1,warA,BCK56342.1,AP023396.1,AMINOGLYCOSIDE,AMINOGLYCOSIDE,NaN,16S rRNA (adenine(1408)-N(1))-methyltransferas...,-,Reference Gene Catalog,-
8418,ACG60763.1,zbmA,ACG60763.1,EU670723.1,BLEOMYCIN,ZORBAMYCIN,19081934,zorbamycin binding protein ZbmA,-,Reference Gene Catalog,-

In [8]:
resfinder

,Gene_accession no.,Class,Phenotype,PMID,Mechanism of resistance,Notes,Required_gene
0,ant(2'')-Ia_1_X04555,Aminoglycoside,"Gentamicin, Tobramycin",3024112,Enzymatic modification,Alternative name aadB,-
1,ant(2'')-Ia_10_HM367617,Aminoglycoside,"Gentamicin, Tobramycin",21873033,Enzymatic modification,-,-
2,ant(2'')-Ia_11_HM367620,Aminoglycoside,"Gentamicin, Tobramycin",21873033,Enzymatic modification,-,-
3,ant(2'')-Ia_12_HQ880250,Aminoglycoside,"Gentamicin, Tobramycin",unpublished,Enzymatic modification,-,-
4,ant(2'')-Ia_13_DQ176450,Aminoglycoside,"Gentamicin, Tobramycin",16304199,Enzymatic modification,-,-
...,...,...,...,...,...,...,...
3207,FloR_8_KU548456,Phenicol,"Chloramphenicol,Florfenicol",Unpublished,Increased efflux,-,-
3208,FloR_9_CP042967,Phenicol,"Chloramphenicol,Florfenicol",Unpublished,Increased efflux,-,-
3209,FloR_10_CP020121,Phenicol,"Chloramphenicol,Florfenicol",Unpublished,Increased efflux,-,-
3210,FloR_11_MG879028,Phenicol,"Chloramphenicol,Florfenicol",Unpublished,Increased efflux,-,-
3211,FloR_12_KX364409,Phenicol,"Chloramphenicol,Florfenicol",Unpublished,Increased efflux,-,-

In [9]:
def split_and_keep_first(s):
    parts = s.split('_')
    if len(parts) > 1:
        return parts[0]
    else:
        return s, ''

In [10]:
def split_and_keep_last(s):
    parts = s.split('_')
    if len(parts) > 1:
        return parts[-1]
    else:
        return s, ''

In [11]:
resfinder["genbank_protein_accession"]="-"
resfinder["product_name"]="-"
resfinder["Database"]="ResFinder Database"
resfinder["ID"]=resfinder["Gene_accession no."]
resfinder["Gene_accession no."]=resfinder["ID"].apply(split_and_keep_first).apply(pd.Series)
resfinder["genbank_nucleotide_accession"]=resfinder["ID"].apply(split_and_keep_last).apply(pd.Series)

In [12]:
resfinder2=resfinder.loc[:,["ID","Gene_accession no.","genbank_protein_accession",
                           "genbank_nucleotide_accession",
                            "Class", "Phenotype", "PMID",
                           "product_name","Mechanism of resistance", "Database", "Notes"]]

In [13]:
# Define new column names and order
new_column_names = {'ID': 'ID', 
                    'Gene_accession no.': 'gene_family', 
                    'Class': 'class',
                     "Phenotype" : "subclass",
                    "PMID" :"pubmed_reference",
                     "Mechanism of resistance" : "Resistance Mechanism",
                     "Database" : "Database",
                     "Notes" : "Notes"}
resfinder2 = resfinder2.rename(columns=new_column_names)

In [14]:
resfinder2.iloc[:5,:]

,ID,gene_family,genbank_protein_accession,genbank_nucleotide_accession,class,subclass,pubmed_reference,product_name,Resistance Mechanism,Database,Notes
0,ant(2'')-Ia_1_X04555,ant(2'')-Ia,-,X04555,Aminoglycoside,"Gentamicin, Tobramycin",3024112,-,Enzymatic modification,ResFinder Database,Alternative name aadB
1,ant(2'')-Ia_10_HM367617,ant(2'')-Ia,-,HM367617,Aminoglycoside,"Gentamicin, Tobramycin",21873033,-,Enzymatic modification,ResFinder Database,-
2,ant(2'')-Ia_11_HM367620,ant(2'')-Ia,-,HM367620,Aminoglycoside,"Gentamicin, Tobramycin",21873033,-,Enzymatic modification,ResFinder Database,-
3,ant(2'')-Ia_12_HQ880250,ant(2'')-Ia,-,HQ880250,Aminoglycoside,"Gentamicin, Tobramycin",unpublished,-,Enzymatic modification,ResFinder Database,-
4,ant(2'')-Ia_13_DQ176450,ant(2'')-Ia,-,DQ176450,Aminoglycoside,"Gentamicin, Tobramycin",16304199,-,Enzymatic modification,ResFinder Database,-

In [15]:
card.iloc[:5,:]

,ARO Accession,CVTERM ID,Model Sequence ID,Model ID,Model Name,ARO Name,Protein Accession,DNA Accession,AMR Gene Family,Drug Class,Resistance Mechanism,CARD Short Name
0,ARO:3005099,43314,6143,3831,23S rRNA (adenine(2058)-N(6))-methyltransferas...,23S rRNA (adenine(2058)-N(6))-methyltransferas...,AAB60941.1,AF002716.1,Erm 23S ribosomal RNA methyltransferase,lincosamide antibiotic;macrolide antibiotic;st...,antibiotic target alteration,Spyo_ErmA_MLSb
1,ARO:3002523,38923,8144,1781,AAC(2')-Ia,AAC(2')-Ia,AAA03550.1,L06156.2,AAC(2'),aminoglycoside antibiotic,antibiotic inactivation,AAC(2')-Ia
2,ARO:3002524,38924,85,746,AAC(2')-Ib,AAC(2')-Ib,AAC44793.1,U41471.1,AAC(2'),aminoglycoside antibiotic,antibiotic inactivation,AAC(2')-Ib
3,ARO:3002525,38925,4719,1246,AAC(2')-Ic,AAC(2')-Ic,CCP42991.1,AL123456.3,AAC(2'),aminoglycoside antibiotic,antibiotic inactivation,AAC(2')-Ic
4,ARO:3002526,38926,228,1415,AAC(2')-Id,AAC(2')-Id,AAB41701.1,U72743.1,AAC(2'),aminoglycoside antibiotic,antibiotic inactivation,AAC(2')-Id

In [16]:
card["pubmed_reference"]="-"
card["Database"]="Card Database"
card["Notes"]=card["ARO Accession"]
card["Drug Subclass"]="-"
card["ID"]=card["Protein Accession"]+"_"+card["ARO Accession"]
card2=card.loc[:,["ID","CARD Short Name",
               "Protein Accession", "DNA Accession",
               "Drug Class", "Drug Subclass","pubmed_reference",
                  "AMR Gene Family","Resistance Mechanism", "Database", "Notes"]]

In [17]:
# Read the card_harmonized.tsv file
card_harmonized = pd.read_csv('/home/argis/Desktop/austin/reslit/site/paper/comparison_other_databases/card/card_harmonized.tsv', delimiter='\t')

# Extract ARO Accession from the Notes column (which contains ARO Accession)
# First, let's check what columns card_harmonized has
print("card_harmonized columns:", card_harmonized.columns.tolist())
print("\ncard_harmonized sample:")
print(card_harmonized.head())

# Create a mapping of ARO Accession to pmid from card_harmonized
# The aro_id column contains the ARO Accession (e.g., "ARO:3007770")
# The pmid column contains the pubmed reference
aro_pmid_mapping = dict(zip(card_harmonized['aro_id'], card_harmonized['pmid']))

# Extract ARO Accession from card2's Notes column and update pubmed_reference
def extract_aro_and_update(row):
    notes = row['Notes']
    # The Notes column contains the ARO Accession (e.g., "ARO:3007770")
    if notes != '-' and pd.notna(notes):
        # Check if this ARO Accession exists in the mapping
        if notes in aro_pmid_mapping:
            pmid = aro_pmid_mapping[notes]
            # Update if pmid is not empty or NaN
            if pd.notna(pmid) and pmid != '':
                return pmid
    return row['pubmed_reference']

# Apply the update
card2['pubmed_reference'] = card2.apply(extract_aro_and_update, axis=1)

print("\ncard2 after update:")
print(card2.head())

card_harmonized columns: ['allele', 'unified_allele', 'gene_name', 'aro_id', 'description', 'antibiotic_class', 'pmid', 'mechanism', 'card_gene_name', 'source', 'match_status']

card_harmonized sample:
            allele   unified_allele      gene_name       aro_id  \
0  aac(6')-Ib-cr10  aac(6')-Ib-cr10  aac(6')-Ib-cr  ARO:3007770
1  aac(6')-Ib-cr11  aac(6')-Ib-cr11  aac(6')-Ib-cr  ARO:3007771
2           aadA14           aadA14    ant(3'')-Ia  ARO:3002614
3           aadA17           aadA17    ant(3'')-Ia  ARO:3002617
4            arr-2            arr-2            arr  ARO:3002847

                                         description  \
0  A fluoroquinolone-acetylating aminoglycoside a...
1  A fluoroquinolone-acetylating aminoglycoside a...
2  aadA14 is a plasmid-encoded aminoglycoside nuc...
3  aadA17 is an integron-encoded aminoglycoside n...
4  arr-2 is an integron-encoded ribosyltransferas...

                                antibiotic_class      pmid  \
0  amikacin|ciprofloxacin|kanamycin A|tobramycin       NaN
1  amikacin|ciprofloxacin|kanamycin A|tobramycin       NaN
2                     spectinomycin|streptomycin  15980396
3                     spectinomycin|streptomycin  22127350
4                                       rifampin  10103210

                mechanism                         card_gene_name source  \
0  enzymatic_inactivation                          AAC(6')-Ib-cr   CARD
1  enzymatic_inactivation                          AAC(6')-Ib-cr   CARD
2  enzymatic_inactivation                            ANT(3'')-Ia   CARD
3  enzymatic_inactivation                            ANT(3'')-Ia   CARD
4  enzymatic_inactivation  rifampin ADP-ribosyltransferase (Arr)   CARD

    match_status
0  matched_exact
1  matched_exact
2  matched_exact
3  matched_exact
4  matched_exact

card2 after update:
                       ID CARD Short Name Protein Accession DNA Accession  \
0  AAB60941.1_ARO:3005099  Spyo_ErmA_MLSb        AAB60941.1    AF002716.1
1  AAA03550.1_ARO:3002523      AAC(2')-Ia        AAA03550.1      L06156.2
2  AAC44793.1_ARO:3002524      AAC(2')-Ib        AAC44793.1      U41471.1
3  CCP42991.1_ARO:3002525      AAC(2')-Ic        CCP42991.1    AL123456.3
4  AAB41701.1_ARO:3002526      AAC(2')-Id        AAB41701.1      U72743.1

                                          Drug Class Drug Subclass  \
0  lincosamide antibiotic;macrolide antibiotic;st...             -
1                          aminoglycoside antibiotic             -
2                          aminoglycoside antibiotic             -
3                          aminoglycoside antibiotic             -
4                          aminoglycoside antibiotic             -

  pubmed_reference                          AMR Gene Family  \
0                -  Erm 23S ribosomal RNA methyltransferase
1          8407825                                  AAC(2')
2          8891143                                  AAC(2')
3          9159528                                  AAC(2')
4          9159528                                  AAC(2')

           Resistance Mechanism       Database        Notes
0  antibiotic target alteration  Card Database  ARO:3005099
1       antibiotic inactivation  Card Database  ARO:3002523
2       antibiotic inactivation  Card Database  ARO:3002524
3       antibiotic inactivation  Card Database  ARO:3002525
4       antibiotic inactivation  Card Database  ARO:3002526

In [34]:
# Define new column names and order
new_column_names = {'ID': 'ID', 
                    'CARD Short Name': 'gene_family',
                    "Protein Accession":"genbank_protein_accession",
                    "DNA Accession":"genbank_nucleotide_accession",
                    'Drug Class': 'class',
                    "Drug Subclass": "subclass",
                    "PMID" :"pubmed_reference",
                    'AMR Gene Family': 'product_name',
                    "Resistance Mechanism" : "Resistance Mechanism",
                     "Database": "Database",
                     'Notes': "Notes"}
card2 = card2.rename(columns=new_column_names)
card2.loc[:,"subclass"] = card2["class"]

In [35]:
card2.iloc[0:5,:]

,ID,gene_family,genbank_protein_accession,genbank_nucleotide_accession,class,subclass,pubmed_reference,product_name,Resistance Mechanism,Database,Notes
0,AAB60941.1_ARO:3005099,Spyo_ErmA_MLSb,AAB60941.1,AF002716.1,lincosamide antibiotic;macrolide antibiotic;st...,lincosamide antibiotic;macrolide antibiotic;st...,-,Erm 23S ribosomal RNA methyltransferase,antibiotic target alteration,Card Database,ARO:3005099
1,AAA03550.1_ARO:3002523,AAC(2')-Ia,AAA03550.1,L06156.2,aminoglycoside antibiotic,aminoglycoside antibiotic,8407825,AAC(2'),antibiotic inactivation,Card Database,ARO:3002523
2,AAC44793.1_ARO:3002524,AAC(2')-Ib,AAC44793.1,U41471.1,aminoglycoside antibiotic,aminoglycoside antibiotic,8891143,AAC(2'),antibiotic inactivation,Card Database,ARO:3002524
3,CCP42991.1_ARO:3002525,AAC(2')-Ic,CCP42991.1,AL123456.3,aminoglycoside antibiotic,aminoglycoside antibiotic,9159528,AAC(2'),antibiotic inactivation,Card Database,ARO:3002525
4,AAB41701.1_ARO:3002526,AAC(2')-Id,AAB41701.1,U72743.1,aminoglycoside antibiotic,aminoglycoside antibiotic,9159528,AAC(2'),antibiotic inactivation,Card Database,ARO:3002526

In [37]:
card2[card2["genbank_protein_accession"]=="BAB82500.1"]

,ID,gene_family,genbank_protein_accession,genbank_nucleotide_accession,class,subclass,pubmed_reference,product_name,Resistance Mechanism,Database,Notes
6142,BAB82500.1_ARO:3000186,tet(M),BAB82500.1,AB039845.1,tetracycline antibiotic,tetracycline antibiotic,19475445,tetracycline-resistant ribosomal protection pr...,antibiotic target protection,Card Database,ARO:3000186

In [38]:
amrFinder2.iloc[:1:2]

,ID,gene_family,genbank_protein_accession,genbank_nucleotide_accession,class,subclass,pubmed_reference,product_name,Resistance Mechanism,Database,Notes
0,CDI94966.1,aac(2')-I(A267),CDI94966.1,HG530068.1,AMINOGLYCOSIDE,GENTAMICIN/TOBRAMYCIN,NaN,aminoglycoside N-acetyltransferase AAC(2')-I(A...,-,Reference Gene Catalog,-

In [39]:
result = pd.concat([amrFinder2, resfinder2, card2], axis=0)

#### Merge the rows of the same proteins

In [40]:
file_path = './nr100_all_proteins_amr.fasta.clstr'  # Replace with your file path
same_proteins={}
with open(file_path, 'r') as file:
    content = file.read()
   # Split the content by '>Cluster' 
    clusters = content.split('>Cluster')[1:]  # Skip the first split part if it's empty
    
    # Regex pattern to find protein IDs
    pattern = re.compile(r'>(\S+)\.\.\.')
    pattern_first = re.compile(r'>(\S+)\.\.\. \*')
    pattern_second = re.compile(r'>(\S+)\.\.\. at')
    # List to store all found protein IDs
    protein_ids = []
    
    # Iterate over each cluster section
    for cluster in clusters:
        matches = pattern.findall(cluster)
        if len(matches)>1:
            first_protein=pattern_first.findall(cluster)
            second_proteins=pattern_second.findall(cluster)
            same_proteins[first_protein[0]]=second_proteins
            print(first_protein[0])
            print(second_proteins)

AAL19305.1
['AAL19305.1_ARO:3000']
AAP43110.2
['AAP43110.2_ARO:3003', 'OqxB_1_EU370913']
QHW08916.1
['tmexD1_1_MK347425']
QQZ45304.1
['tmexD2_1_MN175502']
AAC76298.1
['AAC76298.1_ARO:3000']
AEY83581.1
['AEY83581.1_ARO:3000']
CAA53189.1
['CAA53189.1_ARO:3000']
AIA08936.1
['AIA08936.1_ARO:3000']
AAQ16274.1
['ABA71733.1_ARO:3002']
AAL27444.1
['AAL27444.1_ARO:3002']
AEP40502.2
['AEP40502.2_ARO:3002']
AAD22403.1
['AAD22403.1_ARO:3002']
CNC42950.1
['NP_216393.1_ARO:300']
AQX82825.1
['AQX82857.1_ARO:3004', 'mecD_1_KY013611']
BAI83351.1
['BAI83385.1_ARO:3003', 'mecB_1_NC_011996']
AGC51118.1
['AGC51118.1_ARO:3000']
BAA86650.1
['mecA_2_NC_002951', 'mecA_9_AB505630']
BAB41256.1
['mecA_1_NC_002745', 'mecA_6_BX571856']
BAD24826.1
['mecA_8_NC_007168']
BAJ14745.2
['mecA2_2_AB546780']
CAJ15587.2
['mecA2_1_AM048811']
CAA70425.1
['mecA1_5_AB547234']
AAX35723.1
['mecA1_2_AY820253']
CBZ41940.1
['CCC86795.1_ARO:3001', 'mecC_1_FR821779', 'mecC_2_FR823292']
CDH98053.1
['mecC_4_HG515014']
CAA37477.1
['CAA37477.1_ARO:3002', 'otr(A)_1_X53401']
AKA86814.1
['AKA86814.1_ARO:3003']
optrA_1_KP399637
['optrA_3_KT862780', 'optrA_5_KT862783']
AAA20117.1
['AAA20117.1_ARO:3000', 'tetB(P)_1_NC_010937']
AAF01499.1
['AAF01499.1_ARO:3000', 'tet(T)_1_L42544']
AAV80410.1
['tet(T)_2_AY660530']
APB03219.1
['APB03219.1_ARO:3003']
AAA25293.1
['AAA25293.1_ARO:3000']
AAA62400.1
['tet(Q)_1_L33696']
CAA41552.1
['tet(Q)_2_X58717']
CAA79728.1
['tet(Q)_4_Z21523']
CAD55718.1
['CAD55718.1_ARO:3000', 'tet(36)_1_AJ514254']
CBH51823.1
['CBH51823.1_ARO:3000', 'tet(44)_2_FN594949']
EDS78926.1
['tet(44)_1_NZ_ABDU01']
AAA23033.2
['AAA23033.2_ARO:3000', 'tet(O)_1_M18896']
AAA24784.1
['tet(M)_1_X92947']
AAA26678.1
['tet(M)_6_M21136']
AAA26679.1
['tet(O)_2_M20925']
AAA26830.1
['AAA26830.1_ARO:3007', 'tet_1_M74049']
AAA73978.1
['tet(M)_3_U08812']
AAB05245.1
['tet(M)_5_U58985']
AAL09826.1
['AAL09826.1_ARO:3007', 'tet(W)_2_AY049983']
AAM19211.1
['tet(M)_13_AM990992']
AAO42740.1
['AAO42740.1_ARO:3007', 'tet(O/W/O)-2_1_AY19']
AAR29485.1
['AAR29485.1_ARO:3007']
AAR29969.1
['AAR29969.1_ARO:3007', 'tet(O/W)-2_1_AY4851', 'tet(O/W)-1_1_AY4851']
AAY62597.1
['tet(W)_1_DQ060146']
ABF69686.1
['ABF69686.1_ARO:3007', 'tet(O/W/32/O/W/O)_1']
ABG36114.2
['tet(32)_2_EF626943']
ABG81258.1
['tet(O/W/32/O/W/O)_2']
ABN79417.1
['tet(O/W/O)-3_1_EF06']
ABV82118.1
['ACH87088.1_ARO:3000', 'tet(32)_1_EU722333']
ABW24731.1
['tet(M)_10_EU182585', 'tet(M)_11_JN846696']
AMP42147.1
['AMP42147.1_ARO:3004']
BAB82500.1
['BAB82500.1_ARO:3000']
CAA10975.1
['CAA10975.1_ARO:3000', 'tet(W)_3_AJ427421', 'tet(W)_5_AJ427422']
CAA27977.1
['tet(M)_8_X04388']
CAA39796.1
['tet(M)_9_X56353']
CAA52967.1
['tet(M)_4_X75073']
CAA62436.1
['tet(M)_2_X90939']
CAA69103.1
['tet(O)_3_Y07780']
CAC41371.2
['CAC41371.2_ARO:3007', 'tet(O/32/O)_2_AJ295', 'tet(O/32/O)_6_NG_04']
CAM97380.1
['tet(W/32/O)_1_AM710', 'tet(W/32/O)_2_AM710', 'tet(W/32/O)_3_AM710', 'tet(W/32/O)_4_AM710']
CAX85496.1
['tet(W)_4_FN396364']
CBI48346.1
['tet(M)_7_FN433596']
CBW39442.1
['tet(M)_12_FR671418']
CBZ42067.1
['tet(O/W/32/O)_2_FM1']
ACH58991.1
['ACH58991.1_ARO:3002']
BAB56204.1
['ABQ47844.1_ARO:3000']
ANZ79240.1
['ANZ79240.1_ARO:3004', 'tetA(60)_1_KX000272']
ANZ79241.1
['ANZ79241.1_ARO:3004', 'tetB(60)_1_KX000273']
AET10445.1
['AET10445.1_ARO:3004', 'tetB(46)_1_HQ652506']
AET10444.1
['AET10444.1_ARO:3004', 'tetA(46)_1_HQ652506']
AAA50325.1
['AAA50325.1_ARO:3003', 'ole(B)_1_L36601']
AVX52225.1
['AVX52225.1_ARO:3004', 'mcr-8_1_MG736312']
AXI82464.1
['QIF88262.1_ARO:3007', 'mcr-8.2_1_MH638291']
AXI82467.1
['WP_150823497.1_ARO:', 'mcr-8.3_1_MH598530']
AXR70233.1
['WP_118860654.1_ARO:', 'mcr-8.4_1_MH791448']
QKV49902.1
['mcr-8.5_1_MN836537']
AAD04032.1
['AAD04032.1_ARO:3002']
MCO7070877.1
['MCO7070877.1_ARO:30']
AAB95639.1
['AAB95639.1_ARO:3000', 'vga(B)_1_U82085']
AKC61310.1
['AKC61310.1_ARO:3007']
AAC32027.1
['AAC32027.1_ARO:3002']
ABX00624.1
['ABX00624.1_ARO:3002']
AJP12342.1
['AJP12342.1_ARO:3007']
CAA45050.1
['CAA45050.1_ARO:3002']
AAA26832.1
['AAA26832.1_ARO:3002', 'tlr(C)_1_M57437']
ASK40551.1
['ASK40551.1_ARO:3004', 'mcr-5.1_1_KY807921']
AXF93714.1
['AXF93714.1_ARO:3007', 'mcr-5.3_1_MG886287']
BAA19394.1
['NP_388442.1_ARO:300']
QCT85452.1
['QCT85452.1_ARO:3007', 'mcr-5.4_1_MK965519']
WLY62593.1
['mcr-5.5_1_OR438751']
AVM85875.1
['AVM85875.1_ARO:3004', 'mcr-5.2_1_MG384740']
RTX80047.1
['WP_082039181.1_ARO:']
NWN84933.1
['WP_096809342.1_ARO:']
ATM29809.1
['ATM29809.1_ARO:3004', 'mcr-1.11_1_KY853650']
AVI44920.1
['AVI44920.1_ARO:3004', 'poxtA_1_MF095097']
AGN74946.1
['AGN74946.1_ARO:3003', 'sal(A)_1_KC693025']
AKF16168.1
['AKF16168.1_ARO:3003', 'mcr-1.1_1_KP347127']
ANJ15621.1
['ANJ15621.1_ARO:3004', 'mcr-1.3_1_KU934208']
APM84488.1
['APM84488.1_ARO:3004', 'mcr-1.5_1_KY283125']
APM87143.1
['APM87143.1_ARO:3004', 'mcr-1.4_1_KY041856']
AQK48217.1
['AQK48217.1_ARO:3004', 'mcr-1.6_1_KY352406']
AQQ11622.1
['AQQ11622.1_ARO:3004', 'mcr-1.7_1_KY488488']
AQY61516.1
['AQY61516.1_ARO:3004', 'mcr-1.8_1_KY683842']
ARA74236.1
['WP_109545052.1_ARO:']
ASA49458.1
['WP_213994615.1_ARO:', 'mcr-1.32_1_MF084991']
ASF81896.1
['ASF81896.1_ARO:3004', 'mcr-3.1_1_KY924928']
ASK38392.2
['AVA31022.1_ARO:3004', 'mcr-1.9_1_KY964067']
ASK49940.1
['ASK49940.1_ARO:3004', 'mcr-1.10_1_MF176238']
AST36141.1
['AST36141.1_ARO:3004', 'mcr-3.7_1_MF598077']
AST36144.1
['AST36144.1_ARO:3004', 'mcr-3.9_1_MF598080']
ASU04896.1
['ASU04896.1_ARO:3004', 'mcr-3.5_1_MF489760']
ATQ63376.1
['ATQ63376.1_ARO:3004', 'mcr-3.10_1_MG214531']
AUI38915.1
['AUI38915.1_ARO:3004']
AUN87920.1
['AUN87920.1_ARO:3004', 'mcr-3.11_1_MG489958']
AVK94778.1
['AVK94778.1_ARO:3004']
AVK94779.1
['AVK94779.1_ARO:3004']
AVM85874.1
['AVM85874.1_ARO:3004', 'mcr-1.13_1_MG384739']
AVP73878.1
['ASR73329.1_ARO:3004']
AVP73879.1
['AVK94777.1_ARO:3004']
AVZ47168.1
['AVZ47168.1_ARO:3004', 'mcr-3.12_1_MG564491']
AWY10762.1
['WP_140423331.1_ARO:', 'mcr-3.26_1_MH371139']
AWY10763.1
['AWY10763.1_ARO:3007', 'mcr-3.21_1_NG060582']
AXI82465.1
['AXI82465.1_ARO:3007']
AXI82466.1
['WP_150823496.1_ARO:', 'mcr-3.28_1_MH522717']
BBB21811.1
['BBB21811.1_ARO:3004', 'mcr-1.12_1_LC337668']
MBW0764195.1
['MBW0764195.1_ARO:30']
MBW0770001.1
['MBW0770001.1_ARO:30']
NEU89143.1
['WP_163397051.1_ARO:', 'mcr-1.27_1_NG_06821', 'mcr-1.27_1_JAAGSB01']
OBY14952.1
['ANR95875.1_ARO:3004', 'mcr-1.2_1_KX236309']
OYE10189.1
['OYN70668.1_ARO:3004', 'mcr-3.2_1_NMWW01000']
OYI77277.1
['WP_094321595.1_ARO:', 'mcr-3.24_1_NG060580']
OYK02540.1
['WP_094313523.1_ARO:', 'mcr-3.23_1_NG060583']
QBC35984.1
['WP_129336087.1_ARO:', 'mcr-1.19_1_MK490674']
QBC75464.1
['WP_136512112.1_ARO:', 'mcr-3.29_1_MK521074']
QBG64271.1
['WP_136512110.1_ARO:', 'mcr-1.16_1_MK568462']
QBG64272.1
['WP_136512111.1_ARO:', 'mcr-1.17_1_MK568463']
QCU55424.1
['WP_140423330.1_ARO:', 'mcr-1.21_1_MK965883']
QDO71694.1
['WP_148044477.1_ARO:', 'mcr-1.22_1_MN017134']
QHD57408.1
['WP_160164897.1_ARO:', 'mcr-1.23_1_MN873697']
QHD64700.1
['WP_160164898.1_ARO:', 'mcr-1.24_1_MN879257']
QHD64702.1
['WP_160164899.1_ARO:', 'mcr-1.25_1_MN879259']
QLL99518.1
['WP_181464119.1_ARO:', 'mcr-1.28_1_MT770924']
QLP89638.1
['WP_188331884.1_ARO:']
QLP89639.1
['WP_188331885.1_ARO:']
QNG62238.1
['UUD58346.1_ARO:3007', 'mcr-3.39_1_MT872721']
QNG62239.1
['WP_188331897.1_ARO:', 'mcr-3.40_1_MT872722']
QTY72917.1
['WP_213994614.1_ARO:', 'mcr-1.31_1_MW940640']
SBZ31568.1
['SBZ31568.1_ARO:3004', 'mcr-3.4_1_FLXA01000']
SBZ39991.1
['mcr-3.20_1_NG055493']
SPQ84451.1
['WP_140423329.1_ARO:', 'mcr-1.14_1_LS398440', 'mcr-1.20_1_LS398440']
TNJ68423.1
['WP_094308975.1_ARO:', 'mcr-3.22_1_NG060581']
UAA86711.1
['WP_223106954.1_ARO:']
UDD66098.1
['WP_231236808.1_ARO:', 'mcr-1.34_1_MZ450868']
UGY30527.1
['UGY30527.1_ARO:3007', 'mcr-1.33_1_OL624718']
UPH74550.1
['mcr-1.35_1_ON262566']
WLY62594.1
['mcr-1.36_1_OR438752']
WPO27072.1
['mcr-1.37_1_OR879175']
WP_106743337.1_ARO:
['mcr-1.18_1_PGLM0100']
AWM63467.1_ARO:3007
['mcr-3.19_1_NG055497']
AST36140.1
['AST36140.1_ARO:3004', 'mcr-3.6_1_MF598076']
AST36143.1
['AST36143.1_ARO:3004', 'mcr-3.8_1_MF598078']
ASU10319.1
['ASU10319.1_ARO:3004', 'mcr-3.3_1_MF495680']
AWM11655.1
['WP_111273842.1_ARO:', 'mcr-3.13_1_MH332763']
AWM11656.1
['WP_111273843.1_ARO:', 'mcr-3.14_1_MH332764']
AWM11657.1
['WP_111273844.1_ARO:', 'mcr-3.15_1_MH332765']
AWM11658.1
['WP_111273845.1_ARO:', 'mcr-3.16_1_MH332766']
AWM11659.1
['WP_111273846.1_ARO:', 'mcr-3.17_1_MH332767']
AWM11660.1
['WP_111273847.1_ARO:', 'mcr-3.18_1_MH332768']
AXL06756.1
['WP_116786830.1_ARO:', 'mcr-1.15_1_MG763897']
AXS68550.1
['WP_017778762.1_ARO:', 'mcr-3.27_1_MH131694']
MBA2799562.1
['MBA2799562.1_ARO:30', 'mcr-3.41_1_JACEGL01']
MBO4175406.1
['mcr-9.2_1_MN164032']
NEU93872.1
['WP_034169413.1_ARO:', 'mcr-1.26_1_NG_06821', 'mcr-1.26_1_JAAGSA01']
PNW65753.1
['WP_103252528.1_ARO:', 'mcr-3.25_1_NG060585']
QLP89645.1
['WP_188331890.1_ARO:']
QLP89646.1
['WP_188331891.1_ARO:']
QLQ34536.1
['WP_188331892.1_ARO:', 'mcr-3.33_1_MT791039']
QLQ34537.1
['WP_188331893.1_ARO:', 'mcr-3.34_1_MT791040']
QMT97855.1
['WP_188331894.1_ARO:', 'mcr-3.35_1_MT809044']
QMT97856.1
['WP_188331895.1_ARO:', 'mcr-3.36_1_MT809045']
QMT97858.1
['WP_188331896.1_ARO:', 'mcr-3.37_1_MT809047']
QMU80732.1
['WP_039039919.1_ARO:', 'mcr-3.38_1_MT787344']
UVY70049.1
['mcr-3.42_1_OP297669']
AUR80098.1
['AUR80098.1_ARO:3004', 'mcr-7.1_1_MG267386']
AYW01299.1
['WP_001572373.1_ARO:', 'mcr-9.1_1_MK070339']
MBO4150342.1
['MBO4150342.1_ARO:30', 'mcr-10.4_1_JAGFWU01']
MBO4154571.1
['MBO4154571.1_ARO:30', 'mcr-10.2_1_JAGFWW01']
MBO4158890.1
['MBO4158890.1_ARO:30', 'mcr-10.3_1_JAGFWV01']
QDO66747.1
['QDO66747.1_ARO:3007', 'mcr-10_1_MN179494']
QKF95689.1
['mcr-9.3_1_MT505326']
ULU82661.1
['WP_242934127.1_ARO:', 'mcr-10.5_1_OM638112']
ASK49942.1
['ASK49942.1_ARO:3004', 'mcr-6.1_1_MF176240']
OOS23617.1
['ASK49941.1_ARO:3004', 'mcr-2.2_1_MF176239']
QLP89641.1
['WP_188331887.1_ARO:']
QLP89642.1
['WP_188331889.1_ARO:']
QLP89643.1
['WP_188331888.1_ARO:']
QLP89644.1
['WP_188331886.1_ARO:']
QXM27672.1
['WP_219860731.1_ARO:', 'mcr-2.8_1_MZ520325']
SBV31106.1
['SBV31106.1_ARO:3004', 'mcr-2.1_1_LT598652']
TNK10460.1
['HCJ5800995.1_ARO:30', 'mcr-2.3_1_NQCO02000']
QHA94809.1
['NarB_1_MN590304']
ACX92986.2
['ACX92986.2_ARO:3002', 'vga(D)_1_GQ205627']
AAG08983.1
['vga(A)V_1_AF186237']
AHB37625.1
['AHB37625.1_ARO:3004']
CBY88983.1
['CBY88983.1_ARO:3002', 'vga(E)_1_FR772051']
CAC98997.1
['AEO25219.1_ARO:3004']
AAA26684.1
['AAA26684.1_ARO:3002', 'vga(A)_1_M90056']
ABH10964.1
['ABH10964.1_ARO:3002', 'vga(A)LC_2_DQ823382']
ACX34100.1
['vga(A)LC_1_GQ891882']
CAY33094.2
['CBL58195.1_ARO:3002', 'vga(C)_1_FN806792']
CBB44503.1
['vga(A)_2_FN546261']
CBL58193.1
['vga(A)LC_3_FN806791']
AAC95479.1
['NP_862226.1_ARO:300']
BAA07390.1
['BAA07390.1_ARO:3002', 'tcr3_1_D38215']
ACF70723.1
['ACF70723.1_ARO:3004', 'qepA2_1_EU847537']
ACI16367.1
['qepA_1_FJ167861']
AEZ36150.1
['AEZ36150.1_ARO:3000', 'qepA3_1_JQ064560']
AQM56008.1
['AQX36338.1_ARO:3004', 'qepA4_1_KX580704']
CAA90432.1
['CAA90432.1_ARO:3003']
AAF40764.1
['AAF40764.1_ARO:3003']
SOX29786.1
['SOX29786.1_ARO:3004', 'tva(A)_1_ENA_SOX297']
AMD83542.1
['AMD83542.1_ARO:3007']
AAO43110.1
['AAO43110.1_ARO:3000', 'lsa(A)_1_AY225127']
AAW30456.1
['lsa(A)_3_AY737526']
AXF35727.1
['AXF35727.1_ARO:3005']
AAL05553.1
['AAL05553.1_ARO:3003', 'lsa(E)_1_JX560992']
AAF91071.1
['msr(C)_1_AY004350']
AAK01167.1
['AAK01167.1_ARO:3002', 'msr(C)_2_AF313494']
ACQ82816.1
['ACQ82816.1_ARO:3004']
AEA37904.1
['AEA37904.1_ARO:3003', 'lsa(C)_1_HM990671']
CAE18141.1
['CAE18141.1_ARO:3003', 'lsa(B)_1_AJ579365']
AAN87714.1
['ACB05808.1_ARO:3003', 'msr(E)_1_FR751518']
BAH18719.1
["aph(2'')-Ia_2_AP009"]
BAA34539.1
['msr(A)_2_AB013298']
CAA36304.1
['CAA36304.1_ARO:3000', 'msr(A)_1_X52085']
AAG12999.1
['msr(D)_3_AF227520']
AAK69028.1
['msr(D)_2_AF274302']
DAC81085.1
['DAC81085.1_ARO:3005']
QHW12375.1
['QHW12375.1_ARO:3005']
DAC85638.1
['QNR09092.1_ARO:3007']
QQA64075.1
['QQA64075.1_ARO:3007']
AAA88548.1
['AAA88548.1_ARO:3002', "aac(6')-aph(2'')_1_"]
AAB41059.1
['AAB41059.1_ARO:3002']
CAD60196.1
["aph(2'')-Ia_3_AJ536"]
QHW08917.1
['TOprJ1_1_MK347425', 'TOprJ3_1_LC633285']
QQZ45305.1
['TOprJ2_1_MN175502']
APE19944.1
['APE19944.1_ARO:3007']
CAD70268.1
['CAD70268.1_ARO:3002', 'fexA_1_AJ549214']
CAL64024.1
['fexA_2_AM408573']
BAD58386.1
['BAD58386.1_ARO:3007']
AEV23046.1
['AEV23046.1_ARO:3007', 'fexB_1_JN201336']
CAC14596.1
['CAC14596.1_ARO:3003']
AAL14441.1
['ALX99516.1_ARO:3003']
AAL51021.2
['AAL51021.2_ARO:3002', "ant(3'')-Ii-aac(6')"]
AAB28795.1
['AAB28795.1_ARO:3000']
QJR33972.1
['QJR33972.1_ARO:3007']
AAA22851.1
['AAA22851.1_ARO:3000']
ADE08372.2
['AEM62948.1_ARO:3003']
tet(L)_2_M29725
['tet(L)_4_D00006']
AAU95768.1
['AAU95768.1_ARO:3000']
BAF77019.1
['AAV80464.1_ARO:3000']
AAB05623.1
['AAB05623.1_ARO:3002']
AAB36568.1_ARO:3002
['cmlV_1_U09991']
ABO11759.2
['ABO11759.2_ARO:3004']
ACD35503.1
['ACD35503.1_ARO:3000', 'tet(42)_1_EU523697']
ABA42118.2
['ABA42118.2_ARO:3000']
AAN06707.1_ARO:3000
['tet(A)_6_AF534183']
CAL30186.1
['CAL30186.1_ARO:3002']
AAA20116.1
['AAA20116.1_ARO:3000', 'tetA(P)_2_L20800']
BAA19230.1
['tetA(P)_1_AB054980', 'tetA(P)_3_AB001076']
AAA26057.1
['AAA26057.1_ARO:3002']
AAB84282.1
['AAB84282.1_ARO:3000']
AAF27726.1
['AAF27726.1_ARO:3002']
AAK50387.1
['AAK52606.1_ARO:3002']
ACI28896.1
['ABW91179.1_ARO:3004']
CAA01212.1
['ere(B)_1_A15097']
CAA27626.1
['CAA27626.1_ARO:3000', 'ere(B)_2_X03988']
ABA28305.2
['ABA28305.2_ARO:3000']
CAZ39951.1
['ere(A)_5_FN396877']
CAA11707.1
['CAA11707.1_ARO:3000']
ABA42119.2
['ABA42119.2_ARO:3000']
ADI87853.1
['ADI87853.1_ARO:3004', 'pexA_1_HM537013']
AKQ05891.1
['AKQ05891.1_ARO:3004', 'tet(47)_1_KR857681']
AAG05881.1
['AAG05881.1_ARO:3000']
AAF42063.1
['AAF42063.1_ARO:3000']
AAS13767.1
['AAS13767.1_ARO:3003']
AFO53532.1
['AFO53532.1_ARO:3002']
AAC77293.1
['AAC77293.1_ARO:3001']
CAC80727.1_ARO:3000
['tet(31)_1_GQ283908', 'tet(31)_2_AJ250203']
AAD22144.1
['AAD22144.1_ARO:3002']
ACJ63262.1
['ACJ63262.1_ARO:3003', 'mef(B)_1_FJ196385']
AAC78336.1
['AAC78336.1_ARO:3002', 'ere(A)_2_AF099140', 'ere(A)_4_AF512546']
AAK69613.1
['ere(A)_3_AF326209']
AAL19306.1
['AAL19306.1_ARO:3000']
AKO71461.1
['AKO71461.1_ARO:3004', 'ere(D)_1_KP265721']
BFD45354.1
['BFD45354.1_ARO:3009']
BFF41853.1
['BFF41853.1_ARO:3009']
BFF41854.1
['BFF41854.1_ARO:3009']
BAL43360.1
['BAL43360.1_ARO:3003', 'mef(C)_1_AB571865']
CAD12227.2
['CAD12227.2_ARO:3000']
AAO38247.1
['AAO38247.1_ARO:3000', 'ere(A)_1_AY183453']
AAZ91706.1
['ere(A)_6_DQ157752']
ACI02010.1
['tet(40)_1_FJ158002']
CAM12479.1
['CAM12479.1_ARO:3000', 'tet(40)_2_AM419751']
AAA71915.1
['AAA71915.1_ARO:3000', 'tet(E)_2_L06940']
AAB41436.1
['mef(A)_2_U83667']
AAC44785.1
['AAL73129.1_ARO:3000', 'mef(A)_3_AF227520']
ABI30354.1
['tet(E)_3_CP000645']
CAI94891.2
['mef(A)_1_AJ971089']
AAC98494.1
['floR_1_AF071555']
AAD33243.1
['floR_2_AF118107']
AAG16656.1
['AAG16656.1_ARO:3002']
AAV84883.1
['FloR_4_CP136914']
ABZ01840.1
['ABZ01840.1_ARO:3005', 'CmlA9_1_JN406319']
AIG19992.1
['AIG19992.1_ARO:3005']
AUT06980.1
['WP_104009840.1_ARO:']
ENH92143.1
['WP_003454242.1_ARO:']
FloR_5_CP030849
['FloR_7_CP125947']
AAB59094.1
['tet(B)_3_AJ277653']
AAF74725.1
['AAF74725.1_ARO:3004']
AAL08445.1
['tet(B)_2_AF326777']
BAA78835.1
['tet(B)_1_AP000342']
BAC67143.1
['BAC67143.1_ARO:3000']
AAC43250.1
['tet(H)_4_U00792']
AMP42440.1
['AMP42492.1_ARO:3004', 'tet(59)_1_KU736878']
CAA75663.1
['CAA75663.1_ARO:3000', 'tet(H)_3_Y15510']
CAA76069.1
['tet(H)_1_Y16103']
AAK99679.1
['AAK99679.1_ARO:3000']
AKQ05892.1
['AKQ05892.1_ARO:3004', 'tet(48)_1_KR857682']
QHW12307.1
['QHW12307.1_ARO:3005']
AAD12753.1
['AAD12753.1_ARO:3000', 'tet(J)_2_AF038993']
AJO67548.1
['AJO67548.1_ARO:3005', 'tet(57)_1_KP137702']
EEI47439.1
['tet(J)_1_ACLE010000']
QCO43782.1
['WP_150823478.1_ARO:']
QCO43785.1
['WP_150823479.1_ARO:']
QDO71666.1
['WP_148044441.1_ARO:']
QDY98379.1
['WP_148044463.1_ARO:']
QHN71477.1
['WP_164461297.1_ARO:']
QIM14681.1
['WP_168247886.1_ARO:']
URY98700.1
['URY98700.1_ARO:3008']
XGB73461.1
['XGB73461.1_ARO:3008']
AAG07497.1
['ACQ82807.1_ARO:3002', 'blaPAO_1_AY083595', 'blaPAO_2_FJ666065']
ABR85124.1
['WP_012074328.1_ARO:']
ACQ82806.1
['ACQ82806.1_ARO:3002']
ACQ82809.1
['ACQ82809.1_ARO:3002']
ACQ82810.1
['ACQ82810.1_ARO:3002']
ACQ82811.1
['ACQ82811.1_ARO:3002']
ACQ82812.1
['ACQ82812.1_ARO:3002']
ACQ82813.1
['ACQ82813.1_ARO:3002']
ACQ82814.1
['ACQ82814.1_ARO:3002']
ACQ82815.1
['ACQ82815.1_ARO:3002', 'blaPAO_3_FJ666073']
ACX31161.1
['ACX31161.1_ARO:3005']
ACX31162.1
['WP_009313329.1_ARO:']
ACX31163.1
['WP_063864570.1_ARO:']
ACX31164.1
['ACX31164.1_ARO:3005']
ACX31165.1
['WP_023114693.1_ARO:']
ACX31166.1
['WP_019485213.1_ARO:']
ACX31167.1
['WP_063864571.1_ARO:']
ADC96714.1
['WP_063864572.1_ARO:']
AEM44530.1
['WP_023874922.1_ARO:']
AEM44531.1
['WP_016263090.1_ARO:']
AEM44532.1
['WP_063864575.1_ARO:']
AEM44533.1
['AEM44533.1_ARO:3005']
AEM44535.1
['WP_023115067.1_ARO:']
AEM44536.1
['WP_063864576.1_ARO:']
AEM44537.1
['WP_063864577.1_ARO:']
AIG19969.1
['WP_003110141.1_ARO:']
AIG19970.1
['WP_016562272.1_ARO:', 'blaPAO_4_AY083592']
AIG19971.1
['WP_003137570.1_ARO:']
AIG19973.1
['WP_023100808.1_ARO:']
AIG19974.1
['WP_023092413.1_ARO:']
AIG19975.1
['WP_022580963.1_ARO:']
AIG19976.1
['WP_023091031.1_ARO:']
AIG19977.1
['WP_063864581.1_ARO:']
AIG19978.1
['AIG19978.1_ARO:3005']
AIG19979.1
['WP_063864582.1_ARO:']
AIG19980.1
['AIG19980.1_ARO:3005']
AIG19981.1
['AIG19981.1_ARO:3005']
AIG19982.1
['AIG19982.1_ARO:3005']
AIG19983.1
['WP_043083525.1_ARO:']
AIG19984.1
['AIG19984.1_ARO:3005']
AIG19985.1
['AIG19985.1_ARO:3005']
AIG19986.1
['AIG19986.1_ARO:3005']
AIG19987.1
['AIG19987.1_ARO:3005']
AIG19988.1
['AIG19988.1_ARO:3005']
AIG19989.1
['AIG19989.1_ARO:3005']
AIG19990.1
['AIG19990.1_ARO:3005']
AIG19991.1
['AIG19991.1_ARO:3005']
AIG19993.1
['AIG19993.1_ARO:3005']
AIG19994.1
['AIG19994.1_ARO:3005']
AIG19995.1
['WP_063864583.1_ARO:']
AIG19996.1
['AIG19996.1_ARO:3005']
AIG19997.1
['WP_043089496.1_ARO:']
AIG19998.1
['AIG19998.1_ARO:3005']
AIG19999.1
['AIG19999.1_ARO:3005']
AIG20000.1
['AIG20000.1_ARO:3005']
AIG20001.1
['WP_043104614.1_ARO:']
AIG20002.1
['AIG20002.1_ARO:3005']
AIG20003.1
['AIG20003.1_ARO:3005']
AIG20004.1
['AIG20004.1_ARO:3005']
AIG20005.1
['AIG20005.1_ARO:3005']
AIG20006.1
['AIG20006.1_ARO:3005']
AIG20007.1
['AIG20007.1_ARO:3005']
AIG20008.1
['WP_031630420.1_ARO:']
AIG20009.1
['AIG20009.1_ARO:3005']
AMR55736.1
['WP_063864586.1_ARO:']
AMR55738.1
['WP_063864587.1_ARO:']
AMR55739.1
['WP_063864588.1_ARO:']
AMR55740.1
['WP_061196139.1_ARO:']
ANB78222.1
['WP_023913271.1_ARO:']
ANB78223.1
['WP_063864589.1_ARO:']
ANB78224.1
['WP_058176209.1_ARO:']
ANB78225.1
['WP_063864560.1_ARO:']
ANB78226.1
['WP_063864561.1_ARO:']
ANB78227.1
['WP_031690214.1_ARO:']
ANB78228.1
['WP_058129018.1_ARO:']
ANB78229.1
['WP_063864562.1_ARO:']
ANB78230.1
['WP_063864563.1_ARO:']
ANB78231.1
['WP_063864564.1_ARO:']
ANB78232.1
['WP_063864565.1_ARO:']
ANB78233.1
['WP_029610673.1_ARO:']
ANB78234.1
['WP_063864566.1_ARO:']
ANB78235.1
['WP_063864567.1_ARO:']
ANB78236.1
['WP_063864568.1_ARO:']
ANB78237.1
['WP_063864569.1_ARO:']
AND46540.1
['WP_061189306.1_ARO:']
AND46541.1
['WP_031692400.1_ARO:']
AND46542.1
['WP_061193023.1_ARO:']
AND46543.1
['WP_031687354.1_ARO:']
AND46544.1
['WP_094009806.1_ARO:']
AND46545.1
['WP_058128316.1_ARO:']
AND46546.1
['WP_023089477.1_ARO:']
AND46547.1
['WP_023085632.1_ARO:']
AND46549.1
['WP_023109643.1_ARO:']
AND46550.1
['WP_049321692.1_ARO:']
AND46551.1
['WP_049239252.1_ARO:']
AND46552.1
['WP_053813381.1_ARO:']
ANF28160.1
['WP_064483991.1_ARO:']
ANF28161.1
['WP_064483992.1_ARO:']
ANF28162.1
['WP_064483993.1_ARO:']
ANF28163.1
['WP_064483994.1_ARO:']
ANF28164.1
['WP_064483995.1_ARO:']
ANF28165.1
['WP_064483996.1_ARO:']
ANF28166.1
['WP_064483997.1_ARO:']
ANF28167.1
['WP_064483998.1_ARO:']
ANF28168.1
['WP_064483999.1_ARO:']
ANF28169.1
['WP_064484000.1_ARO:']
ANF28170.1
['WP_064484001.1_ARO:']
ANF28171.1
['WP_064484002.1_ARO:']
ANF28172.1
['WP_064484003.1_ARO:']
ANF28173.1
['WP_064484004.1_ARO:']
ANF28174.1
['WP_064484005.1_ARO:']
ANF28175.1
['WP_064484006.1_ARO:']
ANH22236.1
['WP_064511493.1_ARO:']
ANH22237.1
['WP_064511494.1_ARO:']
ANH22238.1
['WP_064511495.1_ARO:']
ANH22239.1
['WP_064511496.1_ARO:']
ANH22240.1

In [41]:
same_proteins

{'AAL19305.1': ['AAL19305.1_ARO:3000'],
 'AAP43110.2': ['AAP43110.2_ARO:3003', 'OqxB_1_EU370913'],
 'QHW08916.1': ['tmexD1_1_MK347425'],
 'QQZ45304.1': ['tmexD2_1_MN175502'],
 'AAC76298.1': ['AAC76298.1_ARO:3000'],
 'AEY83581.1': ['AEY83581.1_ARO:3000'],
 'CAA53189.1': ['CAA53189.1_ARO:3000'],
 'AIA08936.1': ['AIA08936.1_ARO:3000'],
 'AAQ16274.1': ['ABA71733.1_ARO:3002'],
 'AAL27444.1': ['AAL27444.1_ARO:3002'],
 'AEP40502.2': ['AEP40502.2_ARO:3002'],
 'AAD22403.1': ['AAD22403.1_ARO:3002'],
 'CNC42950.1': ['NP_216393.1_ARO:300'],
 'AQX82825.1': ['AQX82857.1_ARO:3004', 'mecD_1_KY013611'],
 'BAI83351.1': ['BAI83385.1_ARO:3003', 'mecB_1_NC_011996'],
 'AGC51118.1': ['AGC51118.1_ARO:3000'],
 'BAA86650.1': ['mecA_2_NC_002951', 'mecA_9_AB505630'],
 'BAB41256.1': ['mecA_1_NC_002745', 'mecA_6_BX571856'],
 'BAD24826.1': ['mecA_8_NC_007168'],
 'BAJ14745.2': ['mecA2_2_AB546780'],
 'CAJ15587.2': ['mecA2_1_AM048811'],
 'CAA70425.1': ['mecA1_5_AB547234'],
 'AAX35723.1': ['mecA1_2_AY820253'],
 'CBZ41940.1': ['CCC86795.1_ARO:3001', 'mecC_1_FR821779', 'mecC_2_FR823292'],
 'CDH98053.1': ['mecC_4_HG515014'],
 'CAA37477.1': ['CAA37477.1_ARO:3002', 'otr(A)_1_X53401'],
 'AKA86814.1': ['AKA86814.1_ARO:3003'],
 'optrA_1_KP399637': ['optrA_3_KT862780', 'optrA_5_KT862783'],
 'AAA20117.1': ['AAA20117.1_ARO:3000', 'tetB(P)_1_NC_010937'],
 'AAF01499.1': ['AAF01499.1_ARO:3000', 'tet(T)_1_L42544'],
 'AAV80410.1': ['tet(T)_2_AY660530'],
 'APB03219.1': ['APB03219.1_ARO:3003'],
 'AAA25293.1': ['AAA25293.1_ARO:3000'],
 'AAA62400.1': ['tet(Q)_1_L33696'],
 'CAA41552.1': ['tet(Q)_2_X58717'],
 'CAA79728.1': ['tet(Q)_4_Z21523'],
 'CAD55718.1': ['CAD55718.1_ARO:3000', 'tet(36)_1_AJ514254'],
 'CBH51823.1': ['CBH51823.1_ARO:3000', 'tet(44)_2_FN594949'],
 'EDS78926.1': ['tet(44)_1_NZ_ABDU01'],
 'AAA23033.2': ['AAA23033.2_ARO:3000', 'tet(O)_1_M18896'],
 'AAA24784.1': ['tet(M)_1_X92947'],
 'AAA26678.1': ['tet(M)_6_M21136'],
 'AAA26679.1': ['tet(O)_2_M20925'],
 'AAA26830.1': ['AAA26830.1_ARO:3007', 'tet_1_M74049'],
 'AAA73978.1': ['tet(M)_3_U08812'],
 'AAB05245.1': ['tet(M)_5_U58985'],
 'AAL09826.1': ['AAL09826.1_ARO:3007', 'tet(W)_2_AY049983'],
 'AAM19211.1': ['tet(M)_13_AM990992'],
 'AAO42740.1': ['AAO42740.1_ARO:3007', 'tet(O/W/O)-2_1_AY19'],
 'AAR29485.1': ['AAR29485.1_ARO:3007'],
 'AAR29969.1': ['AAR29969.1_ARO:3007',
  'tet(O/W)-2_1_AY4851',
  'tet(O/W)-1_1_AY4851'],
 'AAY62597.1': ['tet(W)_1_DQ060146'],
 'ABF69686.1': ['ABF69686.1_ARO:3007', 'tet(O/W/32/O/W/O)_1'],
 'ABG36114.2': ['tet(32)_2_EF626943'],
 'ABG81258.1': ['tet(O/W/32/O/W/O)_2'],
 'ABN79417.1': ['tet(O/W/O)-3_1_EF06'],
 'ABV82118.1': ['ACH87088.1_ARO:3000', 'tet(32)_1_EU722333'],
 'ABW24731.1': ['tet(M)_10_EU182585', 'tet(M)_11_JN846696'],
 'AMP42147.1': ['AMP42147.1_ARO:3004'],
 'BAB82500.1': ['BAB82500.1_ARO:3000'],
 'CAA10975.1': ['CAA10975.1_ARO:3000',
  'tet(W)_3_AJ427421',
  'tet(W)_5_AJ427422'],
 'CAA27977.1': ['tet(M)_8_X04388'],
 'CAA39796.1': ['tet(M)_9_X56353'],
 'CAA52967.1': ['tet(M)_4_X75073'],
 'CAA62436.1': ['tet(M)_2_X90939'],
 'CAA69103.1': ['tet(O)_3_Y07780'],
 'CAC41371.2': ['CAC41371.2_ARO:3007',
  'tet(O/32/O)_2_AJ295',
  'tet(O/32/O)_6_NG_04'],
 'CAM97380.1': ['tet(W/32/O)_1_AM710',
  'tet(W/32/O)_2_AM710',
  'tet(W/32/O)_3_AM710',
  'tet(W/32/O)_4_AM710'],
 'CAX85496.1': ['tet(W)_4_FN396364'],
 'CBI48346.1': ['tet(M)_7_FN433596'],
 'CBW39442.1': ['tet(M)_12_FR671418'],
 'CBZ42067.1': ['tet(O/W/32/O)_2_FM1'],
 'ACH58991.1': ['ACH58991.1_ARO:3002'],
 'BAB56204.1': ['ABQ47844.1_ARO:3000'],
 'ANZ79240.1': ['ANZ79240.1_ARO:3004', 'tetA(60)_1_KX000272'],
 'ANZ79241.1': ['ANZ79241.1_ARO:3004', 'tetB(60)_1_KX000273'],
 'AET10445.1': ['AET10445.1_ARO:3004', 'tetB(46)_1_HQ652506'],
 'AET10444.1': ['AET10444.1_ARO:3004', 'tetA(46)_1_HQ652506'],
 'AAA50325.1': ['AAA50325.1_ARO:3003', 'ole(B)_1_L36601'],
 'AVX52225.1': ['AVX52225.1_ARO:3004', 'mcr-8_1_MG736312'],
 'AXI82464.1': ['QIF88262.1_ARO:3007', 'mcr-8.2_1_MH638291'],
 'AXI82467.1': ['WP_150823497.1_ARO:', 'mcr-8.3_1_MH598530'],
 'AXR70233.1': ['WP_118860654.1_ARO:', 'mcr-8.4_1_MH791448'],
 'QKV49902.1': ['mcr-8.5_1_MN836537'],
 'AAD04032.1': ['AAD04032.1_ARO:3002'],
 'MCO7070877.1': ['MCO7070877.1_ARO:30'],
 'AAB95639.1': ['AAB95639.1_ARO:3000', 'vga(B)_1_U82085'],
 'AKC61310.1': ['AKC61310.1_ARO:3007'],
 'AAC32027.1': ['AAC32027.1_ARO:3002'],
 'ABX00624.1': ['ABX00624.1_ARO:3002'],
 'AJP12342.1': ['AJP12342.1_ARO:3007'],
 'CAA45050.1': ['CAA45050.1_ARO:3002'],
 'AAA26832.1': ['AAA26832.1_ARO:3002', 'tlr(C)_1_M57437'],
 'ASK40551.1': ['ASK40551.1_ARO:3004', 'mcr-5.1_1_KY807921'],
 'AXF93714.1': ['AXF93714.1_ARO:3007', 'mcr-5.3_1_MG886287'],
 'BAA19394.1': ['NP_388442.1_ARO:300'],
 'QCT85452.1': ['QCT85452.1_ARO:3007', 'mcr-5.4_1_MK965519'],
 'WLY62593.1': ['mcr-5.5_1_OR438751'],
 'AVM85875.1': ['AVM85875.1_ARO:3004', 'mcr-5.2_1_MG384740'],
 'RTX80047.1': ['WP_082039181.1_ARO:'],
 'NWN84933.1': ['WP_096809342.1_ARO:'],
 'ATM29809.1': ['ATM29809.1_ARO:3004', 'mcr-1.11_1_KY853650'],
 'AVI44920.1': ['AVI44920.1_ARO:3004', 'poxtA_1_MF095097'],
 'AGN74946.1': ['AGN74946.1_ARO:3003', 'sal(A)_1_KC693025'],
 'AKF16168.1': ['AKF16168.1_ARO:3003', 'mcr-1.1_1_KP347127'],
 'ANJ15621.1': ['ANJ15621.1_ARO:3004', 'mcr-1.3_1_KU934208'],
 'APM84488.1': ['APM84488.1_ARO:3004', 'mcr-1.5_1_KY283125'],
 'APM87143.1': ['APM87143.1_ARO:3004', 'mcr-1.4_1_KY041856'],
 'AQK48217.1': ['AQK48217.1_ARO:3004', 'mcr-1.6_1_KY352406'],
 'AQQ11622.1': ['AQQ11622.1_ARO:3004', 'mcr-1.7_1_KY488488'],
 'AQY61516.1': ['AQY61516.1_ARO:3004', 'mcr-1.8_1_KY683842'],
 'ARA74236.1': ['WP_109545052.1_ARO:'],
 'ASA49458.1': ['WP_213994615.1_ARO:', 'mcr-1.32_1_MF084991'],
 'ASF81896.1': ['ASF81896.1_ARO:3004', 'mcr-3.1_1_KY924928'],
 'ASK38392.2': ['AVA31022.1_ARO:3004', 'mcr-1.9_1_KY964067'],
 'ASK49940.1': ['ASK49940.1_ARO:3004', 'mcr-1.10_1_MF176238'],
 'AST36141.1': ['AST36141.1_ARO:3004', 'mcr-3.7_1_MF598077'],
 'AST36144.1': ['AST36144.1_ARO:3004', 'mcr-3.9_1_MF598080'],
 'ASU04896.1': ['ASU04896.1_ARO:3004', 'mcr-3.5_1_MF489760'],
 'ATQ63376.1': ['ATQ63376.1_ARO:3004', 'mcr-3.10_1_MG214531'],
 'AUI38915.1': ['AUI38915.1_ARO:3004'],
 'AUN87920.1': ['AUN87920.1_ARO:3004', 'mcr-3.11_1_MG489958'],
 'AVK94778.1': ['AVK94778.1_ARO:3004'],
 'AVK94779.1': ['AVK94779.1_ARO:3004'],
 'AVM85874.1': ['AVM85874.1_ARO:3004', 'mcr-1.13_1_MG384739'],
 'AVP73878.1': ['ASR73329.1_ARO:3004'],
 'AVP73879.1': ['AVK94777.1_ARO:3004'],
 'AVZ47168.1': ['AVZ47168.1_ARO:3004', 'mcr-3.12_1_MG564491'],
 'AWY10762.1': ['WP_140423331.1_ARO:', 'mcr-3.26_1_MH371139'],
 'AWY10763.1': ['AWY10763.1_ARO:3007', 'mcr-3.21_1_NG060582'],
 'AXI82465.1': ['AXI82465.1_ARO:3007'],
 'AXI82466.1': ['WP_150823496.1_ARO:', 'mcr-3.28_1_MH522717'],
 'BBB21811.1': ['BBB21811.1_ARO:3004', 'mcr-1.12_1_LC337668'],
 'MBW0764195.1': ['MBW0764195.1_ARO:30'],
 'MBW0770001.1': ['MBW0770001.1_ARO:30'],
 'NEU89143.1': ['WP_163397051.1_ARO:',
  'mcr-1.27_1_NG_06821',
  'mcr-1.27_1_JAAGSB01'],
 'OBY14952.1': ['ANR95875.1_ARO:3004', 'mcr-1.2_1_KX236309'],
 'OYE10189.1': ['OYN70668.1_ARO:3004', 'mcr-3.2_1_NMWW01000'],
 'OYI77277.1': ['WP_094321595.1_ARO:', 'mcr-3.24_1_NG060580'],
 'OYK02540.1': ['WP_094313523.1_ARO:', 'mcr-3.23_1_NG060583'],
 'QBC35984.1': ['WP_129336087.1_ARO:', 'mcr-1.19_1_MK490674'],
 'QBC75464.1': ['WP_136512112.1_ARO:', 'mcr-3.29_1_MK521074'],
 'QBG64271.1': ['WP_136512110.1_ARO:', 'mcr-1.16_1_MK568462'],
 'QBG64272.1': ['WP_136512111.1_ARO:', 'mcr-1.17_1_MK568463'],
 'QCU55424.1': ['WP_140423330.1_ARO:', 'mcr-1.21_1_MK965883'],
 'QDO71694.1': ['WP_148044477.1_ARO:', 'mcr-1.22_1_MN017134'],
 'QHD57408.1': ['WP_160164897.1_ARO:', 'mcr-1.23_1_MN873697'],
 'QHD64700.1': ['WP_160164898.1_ARO:', 'mcr-1.24_1_MN879257'],
 'QHD64702.1': ['WP_160164899.1_ARO:', 'mcr-1.25_1_MN879259'],
 'QLL99518.1': ['WP_181464119.1_ARO:', 'mcr-1.28_1_MT770924'],
 'QLP89638.1': ['WP_188331884.1_ARO:'],
 'QLP89639.1': ['WP_188331885.1_ARO:'],
 'QNG62238.1': ['UUD58346.1_ARO:3007', 'mcr-3.39_1_MT872721'],
 'QNG62239.1': ['WP_188331897.1_ARO:', 'mcr-3.40_1_MT872722'],
 'QTY72917.1': ['WP_213994614.1_ARO:', 'mcr-1.31_1_MW940640'],
 'SBZ31568.1': ['SBZ31568.1_ARO:3004', 'mcr-3.4_1_FLXA01000'],
 'SBZ39991.1': ['mcr-3.20_1_NG055493'],
 'SPQ84451.1': ['WP_140423329.1_ARO:',
  'mcr-1.14_1_LS398440',
  'mcr-1.20_1_LS398440'],
 'TNJ68423.1': ['WP_094308975.1_ARO:', 'mcr-3.22_1_NG060581'],
 'UAA86711.1': ['WP_223106954.1_ARO:'],
 'UDD66098.1': ['WP_231236808.1_ARO:', 'mcr-1.34_1_MZ450868'],
 'UGY30527.1': ['UGY30527.1_ARO:3007', 'mcr-1.33_1_OL624718'],
 'UPH74550.1': ['mcr-1.35_1_ON262566'],
 'WLY62594.1': ['mcr-1.36_1_OR438752'],
 'WPO27072.1': ['mcr-1.37_1_OR879175'],
 'WP_106743337.1_ARO:': ['mcr-1.18_1_PGLM0100'],
 'AWM63467.1_ARO:3007': ['mcr-3.19_1_NG055497'],
 'AST36140.1': ['AST36140.1_ARO:3004', 'mcr-3.6_1_MF598076'],
 'AST36143.1': ['AST36143.1_ARO:3004', 'mcr-3.8_1_MF598078'],
 'ASU10319.1': ['ASU10319.1_ARO:3004', 'mcr-3.3_1_MF495680'],
 'AWM11655.1': ['WP_111273842.1_ARO:', 'mcr-3.13_1_MH332763'],
 'AWM11656.1': ['WP_111273843.1_ARO:', 'mcr-3.14_1_MH332764'],
 'AWM11657.1': ['WP_111273844.1_ARO:', 'mcr-3.15_1_MH332765'],
 'AWM11658.1': ['WP_111273845.1_ARO:', 'mcr-3.16_1_MH332766'],
 'AWM11659.1': ['WP_111273846.1_ARO:', 'mcr-3.17_1_MH332767'],
 'AWM11660.1': ['WP_111273847.1_ARO:', 'mcr-3.18_1_MH332768'],
 'AXL06756.1': ['WP_116786830.1_ARO:', 'mcr-1.15_1_MG763897'],
 'AXS68550.1': ['WP_017778762.1_ARO:', 'mcr-3.27_1_MH131694'],
 'MBA2799562.1': ['MBA2799562.1_ARO:30', 'mcr-3.41_1_JACEGL01'],
 'MBO4175406.1': ['mcr-9.2_1_MN164032'],
 'NEU93872.1': ['WP_034169413.1_ARO:',
  'mcr-1.26_1_NG_06821',
  'mcr-1.26_1_JAAGSA01'],
 'PNW65753.1': ['WP_103252528.1_ARO:', 'mcr-3.25_1_NG060585'],
 'QLP89645.1': ['WP_188331890.1_ARO:'],
 'QLP89646.1': ['WP_188331891.1_ARO:'],
 'QLQ34536.1': ['WP_188331892.1_ARO:', 'mcr-3.33_1_MT791039'],
 'QLQ34537.1': ['WP_188331893.1_ARO:', 'mcr-3.34_1_MT791040'],
 'QMT97855.1': ['WP_188331894.1_ARO:', 'mcr-3.35_1_MT809044'],
 'QMT97856.1': ['WP_188331895.1_ARO:', 'mcr-3.36_1_MT809045'],
 'QMT97858.1': ['WP_188331896.1_ARO:', 'mcr-3.37_1_MT809047'],
 'QMU80732.1': ['WP_039039919.1_ARO:', 'mcr-3.38_1_MT787344'],
 'UVY70049.1': ['mcr-3.42_1_OP297669'],
 'AUR80098.1': ['AUR80098.1_ARO:3004', 'mcr-7.1_1_MG267386'],
 'AYW01299.1': ['WP_001572373.1_ARO:', 'mcr-9.1_1_MK070339'],
 'MBO4150342.1': ['MBO4150342.1_ARO:30', 'mcr-10.4_1_JAGFWU01'],
 'MBO4154571.1': ['MBO4154571.1_ARO:30', 'mcr-10.2_1_JAGFWW01'],
 'MBO4158890.1': ['MBO4158890.1_ARO:30', 'mcr-10.3_1_JAGFWV01'],
 'QDO66747.1': ['QDO66747.1_ARO:3007', 'mcr-10_1_MN179494'],
 'QKF95689.1': ['mcr-9.3_1_MT505326'],
 'ULU82661.1': ['WP_242934127.1_ARO:', 'mcr-10.5_1_OM638112'],
 'ASK49942.1': ['ASK49942.1_ARO:3004', 'mcr-6.1_1_MF176240'],
 'OOS23617.1': ['ASK49941.1_ARO:3004', 'mcr-2.2_1_MF176239'],
 'QLP89641.1': ['WP_188331887.1_ARO:'],
 'QLP89642.1': ['WP_188331889.1_ARO:'],
 'QLP89643.1': ['WP_188331888.1_ARO:'],
 'QLP89644.1': ['WP_188331886.1_ARO:'],
 'QXM27672.1': ['WP_219860731.1_ARO:', 'mcr-2.8_1_MZ520325'],
 'SBV31106.1': ['SBV31106.1_ARO:3004', 'mcr-2.1_1_LT598652'],
 'TNK10460.1': ['HCJ5800995.1_ARO:30', 'mcr-2.3_1_NQCO02000'],
 'QHA94809.1': ['NarB_1_MN590304'],
 'ACX92986.2': ['ACX92986.2_ARO:3002', 'vga(D)_1_GQ205627'],
 'AAG08983.1': ['vga(A)V_1_AF186237'],
 'AHB37625.1': ['AHB37625.1_ARO:3004'],
 'CBY88983.1': ['CBY88983.1_ARO:3002', 'vga(E)_1_FR772051'],
 'CAC98997.1': ['AEO25219.1_ARO:3004'],
 'AAA26684.1': ['AAA26684.1_ARO:3002', 'vga(A)_1_M90056'],
 'ABH10964.1': ['ABH10964.1_ARO:3002', 'vga(A)LC_2_DQ823382'],
 'ACX34100.1': ['vga(A)LC_1_GQ891882'],
 'CAY33094.2': ['CBL58195.1_ARO:3002', 'vga(C)_1_FN806792'],
 'CBB44503.1': ['vga(A)_2_FN546261'],
 'CBL58193.1': ['vga(A)LC_3_FN806791'],
 'AAC95479.1': ['NP_862226.1_ARO:300'],
 'BAA07390.1': ['BAA07390.1_ARO:3002', 'tcr3_1_D38215'],
 'ACF70723.1': ['ACF70723.1_ARO:3004', 'qepA2_1_EU847537'],
 'ACI16367.1': ['qepA_1_FJ167861'],
 'AEZ36150.1': ['AEZ36150.1_ARO:3000', 'qepA3_1_JQ064560'],
 'AQM56008.1': ['AQX36338.1_ARO:3004', 'qepA4_1_KX580704'],
 'CAA90432.1': ['CAA90432.1_ARO:3003'],
 'AAF40764.1': ['AAF40764.1_ARO:3003'],
 'SOX29786.1': ['SOX29786.1_ARO:3004', 'tva(A)_1_ENA_SOX297'],
 'AMD83542.1': ['AMD83542.1_ARO:3007'],
 'AAO43110.1': ['AAO43110.1_ARO:3000', 'lsa(A)_1_AY225127'],
 'AAW30456.1': ['lsa(A)_3_AY737526'],
 'AXF35727.1': ['AXF35727.1_ARO:3005'],
 'AAL05553.1': ['AAL05553.1_ARO:3003', 'lsa(E)_1_JX560992'],
 'AAF91071.1': ['msr(C)_1_AY004350'],
 'AAK01167.1': ['AAK01167.1_ARO:3002', 'msr(C)_2_AF313494'],
 'ACQ82816.1': ['ACQ82816.1_ARO:3004'],
 'AEA37904.1': ['AEA37904.1_ARO:3003', 'lsa(C)_1_HM990671'],
 'CAE18141.1': ['CAE18141.1_ARO:3003', 'lsa(B)_1_AJ579365'],
 'AAN87714.1': ['ACB05808.1_ARO:3003', 'msr(E)_1_FR751518'],
 'BAH18719.1': ["aph(2'')-Ia_2_AP009"],
 'BAA34539.1': ['msr(A)_2_AB013298'],
 'CAA36304.1': ['CAA36304.1_ARO:3000', 'msr(A)_1_X52085'],
 'AAG12999.1': ['msr(D)_3_AF227520'],
 'AAK69028.1': ['msr(D)_2_AF274302'],
 'DAC81085.1': ['DAC81085.1_ARO:3005'],
 'QHW12375.1': ['QHW12375.1_ARO:3005'],
 'DAC85638.1': ['QNR09092.1_ARO:3007'],
 'QQA64075.1': ['QQA64075.1_ARO:3007'],
 'AAA88548.1': ['AAA88548.1_ARO:3002', "aac(6')-aph(2'')_1_"],
 'AAB41059.1': ['AAB41059.1_ARO:3002'],
 'CAD60196.1': ["aph(2'')-Ia_3_AJ536"],
 'QHW08917.1': ['TOprJ1_1_MK347425', 'TOprJ3_1_LC633285'],
 'QQZ45305.1': ['TOprJ2_1_MN175502'],
 'APE19944.1': ['APE19944.1_ARO:3007'],
 'CAD70268.1': ['CAD70268.1_ARO:3002', 'fexA_1_AJ549214'],
 'CAL64024.1': ['fexA_2_AM408573'],
 'BAD58386.1': ['BAD58386.1_ARO:3007'],
 'AEV23046.1': ['AEV23046.1_ARO:3007', 'fexB_1_JN201336'],
 'CAC14596.1': ['CAC14596.1_ARO:3003'],
 'AAL14441.1': ['ALX99516.1_ARO:3003'],
 'AAL51021.2': ['AAL51021.2_ARO:3002', "ant(3'')-Ii-aac(6')"],
 'AAB28795.1': ['AAB28795.1_ARO:3000'],
 'QJR33972.1': ['QJR33972.1_ARO:3007'],
 'AAA22851.1': ['AAA22851.1_ARO:3000'],
 'ADE08372.2': ['AEM62948.1_ARO:3003'],
 'tet(L)_2_M29725': ['tet(L)_4_D00006'],
 'AAU95768.1': ['AAU95768.1_ARO:3000'],
 'BAF77019.1': ['AAV80464.1_ARO:3000'],
 'AAB05623.1': ['AAB05623.1_ARO:3002'],
 'AAB36568.1_ARO:3002': ['cmlV_1_U09991'],
 'ABO11759.2': ['ABO11759.2_ARO:3004'],
 'ACD35503.1': ['ACD35503.1_ARO:3000', 'tet(42)_1_EU523697'],
 'ABA42118.2': ['ABA42118.2_ARO:3000'],
 'AAN06707.1_ARO:3000': ['tet(A)_6_AF534183'],
 'CAL30186.1': ['CAL30186.1_ARO:3002'],
 'AAA20116.1': ['AAA20116.1_ARO:3000', 'tetA(P)_2_L20800'],
 'BAA19230.1': ['tetA(P)_1_AB054980', 'tetA(P)_3_AB001076'],
 'AAA26057.1': ['AAA26057.1_ARO:3002'],
 'AAB84282.1': ['AAB84282.1_ARO:3000'],
 'AAF27726.1': ['AAF27726.1_ARO:3002'],
 'AAK50387.1': ['AAK52606.1_ARO:3002'],
 'ACI28896.1': ['ABW91179.1_ARO:3004'],
 'CAA01212.1': ['ere(B)_1_A15097'],
 'CAA27626.1': ['CAA27626.1_ARO:3000', 'ere(B)_2_X03988'],
 'ABA28305.2': ['ABA28305.2_ARO:3000'],
 'CAZ39951.1': ['ere(A)_5_FN396877'],
 'CAA11707.1': ['CAA11707.1_ARO:3000'],
 'ABA42119.2': ['ABA42119.2_ARO:3000'],
 'ADI87853.1': ['ADI87853.1_ARO:3004', 'pexA_1_HM537013'],
 'AKQ05891.1': ['AKQ05891.1_ARO:3004', 'tet(47)_1_KR857681'],
 'AAG05881.1': ['AAG05881.1_ARO:3000'],
 'AAF42063.1': ['AAF42063.1_ARO:3000'],
 'AAS13767.1': ['AAS13767.1_ARO:3003'],
 'AFO53532.1': ['AFO53532.1_ARO:3002'],
 'AAC77293.1': ['AAC77293.1_ARO:3001'],
 'CAC80727.1_ARO:3000': ['tet(31)_1_GQ283908', 'tet(31)_2_AJ250203'],
 'AAD22144.1': ['AAD22144.1_ARO:3002'],
 'ACJ63262.1': ['ACJ63262.1_ARO:3003', 'mef(B)_1_FJ196385'],
 'AAC78336.1': ['AAC78336.1_ARO:3002',
  'ere(A)_2_AF099140',
  'ere(A)_4_AF512546'],
 'AAK69613.1': ['ere(A)_3_AF326209'],
 'AAL19306.1': ['AAL19306.1_ARO:3000'],
 'AKO71461.1': ['AKO71461.1_ARO:3004', 'ere(D)_1_KP265721'],
 'BFD45354.1': ['BFD45354.1_ARO:3009'],
 'BFF41853.1': ['BFF41853.1_ARO:3009'],
 'BFF41854.1': ['BFF41854.1_ARO:3009'],
 'BAL43360.1': ['BAL43360.1_ARO:3003', 'mef(C)_1_AB571865'],
 'CAD12227.2': ['CAD12227.2_ARO:3000'],
 'AAO38247.1': ['AAO38247.1_ARO:3000', 'ere(A)_1_AY183453'],
 'AAZ91706.1': ['ere(A)_6_DQ157752'],
 'ACI02010.1': ['tet(40)_1_FJ158002'],
 'CAM12479.1': ['CAM12479.1_ARO:3000', 'tet(40)_2_AM419751'],
 'AAA71915.1': ['AAA71915.1_ARO:3000', 'tet(E)_2_L06940'],
 'AAB41436.1': ['mef(A)_2_U83667'],
 'AAC44785.1': ['AAL73129.1_ARO:3000', 'mef(A)_3_AF227520'],
 'ABI30354.1': ['tet(E)_3_CP000645'],
 'CAI94891.2': ['mef(A)_1_AJ971089'],
 'AAC98494.1': ['floR_1_AF071555'],
 'AAD33243.1': ['floR_2_AF118107'],
 'AAG16656.1': ['AAG16656.1_ARO:3002'],
 'AAV84883.1': ['FloR_4_CP136914'],
 'ABZ01840.1': ['ABZ01840.1_ARO:3005', 'CmlA9_1_JN406319'],
 'AIG19992.1': ['AIG19992.1_ARO:3005'],
 'AUT06980.1': ['WP_104009840.1_ARO:'],
 'ENH92143.1': ['WP_003454242.1_ARO:'],
 'FloR_5_CP030849': ['FloR_7_CP125947'],
 'AAB59094.1': ['tet(B)_3_AJ277653'],
 'AAF74725.1': ['AAF74725.1_ARO:3004'],
 'AAL08445.1': ['tet(B)_2_AF326777'],
 'BAA78835.1': ['tet(B)_1_AP000342'],
 'BAC67143.1': ['BAC67143.1_ARO:3000'],
 'AAC43250.1': ['tet(H)_4_U00792'],
 'AMP42440.1': ['AMP42492.1_ARO:3004', 'tet(59)_1_KU736878'],
 'CAA75663.1': ['CAA75663.1_ARO:3000', 'tet(H)_3_Y15510'],
 'CAA76069.1': ['tet(H)_1_Y16103'],
 'AAK99679.1': ['AAK99679.1_ARO:3000'],
 'AKQ05892.1': ['AKQ05892.1_ARO:3004', 'tet(48)_1_KR857682'],
 'QHW12307.1': ['QHW12307.1_ARO:3005'],
 'AAD12753.1': ['AAD12753.1_ARO:3000', 'tet(J)_2_AF038993'],
 'AJO67548.1': ['AJO67548.1_ARO:3005', 'tet(57)_1_KP137702'],
 'EEI47439.1': ['tet(J)_1_ACLE010000'],
 'QCO43782.1': ['WP_150823478.1_ARO:'],
 'QCO43785.1': ['WP_150823479.1_ARO:'],
 'QDO71666.1': ['WP_148044441.1_ARO:'],
 'QDY98379.1': ['WP_148044463.1_ARO:'],
 'QHN71477.1': ['WP_164461297.1_ARO:'],
 'QIM14681.1': ['WP_168247886.1_ARO:'],
 'URY98700.1': ['URY98700.1_ARO:3008'],
 'XGB73461.1': ['XGB73461.1_ARO:3008'],
 'AAG07497.1': ['ACQ82807.1_ARO:3002',
  'blaPAO_1_AY083595',
  'blaPAO_2_FJ666065'],
 'ABR85124.1': ['WP_012074328.1_ARO:'],
 'ACQ82806.1': ['ACQ82806.1_ARO:3002'],
 'ACQ82809.1': ['ACQ82809.1_ARO:3002'],
 'ACQ82810.1': ['ACQ82810.1_ARO:3002'],
 'ACQ82811.1': ['ACQ82811.1_ARO:3002'],
 'ACQ82812.1': ['ACQ82812.1_ARO:3002'],
 'ACQ82813.1': ['ACQ82813.1_ARO:3002'],
 'ACQ82814.1': ['ACQ82814.1_ARO:3002'],
 'ACQ82815.1': ['ACQ82815.1_ARO:3002', 'blaPAO_3_FJ666073'],
 'ACX31161.1': ['ACX31161.1_ARO:3005'],
 'ACX31162.1': ['WP_009313329.1_ARO:'],
 'ACX31163.1': ['WP_063864570.1_ARO:'],
 'ACX31164.1': ['ACX31164.1_ARO:3005'],
 'ACX31165.1': ['WP_023114693.1_ARO:'],
 'ACX31166.1': ['WP_019485213.1_ARO:'],
 'ACX31167.1': ['WP_063864571.1_ARO:'],
 'ADC96714.1': ['WP_063864572.1_ARO:'],
 'AEM44530.1': ['WP_023874922.1_ARO:'],
 'AEM44531.1': ['WP_016263090.1_ARO:'],
 'AEM44532.1': ['WP_063864575.1_ARO:'],
 'AEM44533.1': ['AEM44533.1_ARO:3005'],
 'AEM44535.1': ['WP_023115067.1_ARO:'],
 'AEM44536.1': ['WP_063864576.1_ARO:'],
 'AEM44537.1': ['WP_063864577.1_ARO:'],
 'AIG19969.1': ['WP_003110141.1_ARO:'],
 'AIG19970.1': ['WP_016562272.1_ARO:', 'blaPAO_4_AY083592'],
 'AIG19971.1': ['WP_003137570.1_ARO:'],
 'AIG19973.1': ['WP_023100808.1_ARO:'],
 'AIG19974.1': ['WP_023092413.1_ARO:'],
 'AIG19975.1': ['WP_022580963.1_ARO:'],
 'AIG19976.1': ['WP_023091031.1_ARO:'],
 'AIG19977.1': ['WP_063864581.1_ARO:'],
 'AIG19978.1': ['AIG19978.1_ARO:3005'],
 'AIG19979.1': ['WP_063864582.1_ARO:'],
 'AIG19980.1': ['AIG19980.1_ARO:3005'],
 'AIG19981.1': ['AIG19981.1_ARO:3005'],
 'AIG19982.1': ['AIG19982.1_ARO:3005'],
 'AIG19983.1': ['WP_043083525.1_ARO:'],
 'AIG19984.1': ['AIG19984.1_ARO:3005'],
 'AIG19985.1': ['AIG19985.1_ARO:3005'],
 'AIG19986.1': ['AIG19986.1_ARO:3005'],
 'AIG19987.1': ['AIG19987.1_ARO:3005'],
 'AIG19988.1': ['AIG19988.1_ARO:3005'],
 'AIG19989.1': ['AIG19989.1_ARO:3005'],
 'AIG19990.1': ['AIG19990.1_ARO:3005'],
 'AIG19991.1': ['AIG19991.1_ARO:3005'],
 'AIG19993.1': ['AIG19993.1_ARO:3005'],
 'AIG19994.1': ['AIG19994.1_ARO:3005'],
 'AIG19995.1': ['WP_063864583.1_ARO:'],
 'AIG19996.1': ['AIG19996.1_ARO:3005'],
 'AIG19997.1': ['WP_043089496.1_ARO:'],
 'AIG19998.1': ['AIG19998.1_ARO:3005'],
 'AIG19999.1': ['AIG19999.1_ARO:3005'],
 'AIG20000.1': ['AIG20000.1_ARO:3005'],
 'AIG20001.1': ['WP_043104614.1_ARO:'],
 'AIG20002.1': ['AIG20002.1_ARO:3005'],

In [42]:
result.loc[result["ID"]=="BAB82500.1"]

,ID,gene_family,genbank_protein_accession,genbank_nucleotide_accession,class,subclass,pubmed_reference,product_name,Resistance Mechanism,Database,Notes
8007,BAB82500.1,tet(M),BAB82500.1,AB039845.1,TETRACYCLINE,TETRACYCLINE,19475445,tetracycline resistance ribosomal protection p...,-,Reference Gene Catalog,-

In [43]:
result_all=result
result_all['ID'] = result['ID'].fillna('')
result_all = result_all.reset_index(drop=True)
result_all = result_all.reindex(list(range(len(result["ID"]))))

In [44]:
for key, value in same_proteins.items():
    escaped_key = re.escape(key)
    row_1 = result_all.loc[result_all["ID"].str.contains(escaped_key, na=False)]
    
    if row_1.empty:
        continue
    
    row_1_index = row_1.index[0]
    
    # Create a regex pattern from the name list
    escaped_patterns = [re.escape(pattern) for pattern in value]
    combined_pattern = '|'.join(escaped_patterns)
    rows_other = result_all.loc[result_all["ID"].str.contains(combined_pattern, na=False)]
    
    if rows_other.empty:
        continue
    
    if len(value) == 1:
        for col in result_all.columns:
            if col != 'ID' and col != 'Database':
                if result_all.at[row_1_index, col] == '-':
                    result_all.at[row_1_index, col] = rows_other.iloc[0][col]
        result_all.at[row_1_index, "Database"] = result_all.at[row_1_index, "Database"] + "," + rows_other.iloc[0]["Database"]
        result_all.at[row_1_index, "subclass"] = result_all.at[row_1_index, "subclass"] + "," + rows_other.iloc[0]["subclass"]
        
    else:
        #print("Yeah")
        for col in result_all.columns:
            if col != 'ID' and col != 'Database':
                if result_all.at[row_1_index, col] == '-':
                    if rows_other.iloc[0][col] != '-':
                        result_all.at[row_1_index, col] = rows_other.iloc[0][col]
                    else:
                        result_all.at[row_1_index, col] = rows_other.iloc[1][col]
        result_all.at[row_1_index, "Database"] = result_all.at[row_1_index, "Database"] + "," + rows_other.iloc[0]["Database"] + "," + rows_other.iloc[1]["Database"]
        result_all.at[row_1_index, "subclass"] = result_all.at[row_1_index, "subclass"] + "," + rows_other.iloc[0]["subclass"] + "," + rows_other.iloc[1]["subclass"]

In [45]:
# Function to process each row
def process_row(row):
    # Split the subclass string into individual words using , ; /
    if pd.isna(row["subclass"]) or row["subclass"] == "NaN":
        return "NaN"  # Return "NaN" string if subclass is NaN
    else: 
        words = [word.strip() for word in re.split(r'[;,/]', row["subclass"]) if word.strip()]

        # Convert to uppercase and keep only unique words, excluding "-"
        unique_words = set(word.upper() for word in words if word != "-")

        # Join the unique words into a single string with commas
        return ", ".join(unique_words)


# Apply the function to each row in the "subclass" column
result_all["subclass"] = result_all.apply(lambda row: process_row(row), axis=1)

In [46]:
result

,ID,gene_family,genbank_protein_accession,genbank_nucleotide_accession,class,subclass,pubmed_reference,product_name,Resistance Mechanism,Database,Notes
0,CDI94966.1,aac(2')-I(A267),CDI94966.1,HG530068.1,AMINOGLYCOSIDE,GENTAMICIN/TOBRAMYCIN,NaN,aminoglycoside N-acetyltransferase AAC(2')-I(A...,-,Reference Gene Catalog,-
1,BAM16262.1,aac(2')-IIa,BAM16262.1,AB669090.1,AMINOGLYCOSIDE,KASUGAMYCIN,22660700,kasugamycin N-acetyltransferase AAC(2')-IIa,-,Reference Gene Catalog,-
2,APB03221.1,aac(2')-IIb,APB03221.1,KX531051.1,AMINOGLYCOSIDE,KASUGAMYCIN,27929110,kasugamycin N-acetyltransferase AAC(2')-IIb,-,Reference Gene Catalog,-
3,AAA03550.1,aac(2')-Ia,AAA03550.1,L06156.2,AMINOGLYCOSIDE,GENTAMICIN/PLAZOMICIN/TOBRAMYCIN,"8407825,40178262",aminoglycoside N-acetyltransferase AAC(2')-Ia,-,Reference Gene Catalog,-
4,AAC44793.1,aac(2')-Ib,AAC44793.1,U41471.1,AMINOGLYCOSIDE,GENTAMICIN/TOBRAMYCIN,8891143,aminoglycoside N-acetyltransferase AAC(2')-Ib,-,Reference Gene Catalog,-
...,...,...,...,...,...,...,...,...,...,...,...
6440,CAB13167.1_ARO:3003064,ykkD,CAB13167.1,AL009126.1,aminoglycoside antibiotic;phenicol antibiotic;...,aminoglycoside antibiotic;phenicol antibiotic;...,10735877,small multidrug resistance (SMR) antibiotic ef...,antibiotic efflux,Card Database,ARO:3003064
6441,QIU91361.1_ARO:3009096,YOC-1,QIU91361.1,CP050811.1,cephalosporin,cephalosporin,-,YOC beta-lactamase,antibiotic inactivation,Card Database,ARO:3009096
6442,AAC75271.1_ARO:3003952,YojI,AAC75271.1,U00096.3,peptide antibiotic,peptide antibiotic,15866933,ATP-binding cassette (ABC) antibiotic efflux pump,antibiotic efflux,Card Database,ARO:3003952
6443,ABA70720.1_ARO:3005035,YRC-1,ABA70720.1,DQ185144.1,cephalosporin;penicillin beta-lactam,cephalosporin;penicillin beta-lactam,16553832,YRC beta-lactamase,antibiotic inactivation,Card Database,ARO:3005035
6444,WP_013992183.1_ARO:3007006,ZOG-1,WP_013992183.1,NG_057434.1,carbapenem,carbapenem,-,ZOG beta-lactamase,antibiotic inactivation,Card Database,ARO:3007006

In [32]:
result_all

,ID,gene_family,genbank_protein_accession,genbank_nucleotide_accession,class,subclass,pubmed_reference,product_name,Resistance Mechanism,Database,Notes
0,CDI94966.1,aac(2')-I(A267),CDI94966.1,HG530068.1,AMINOGLYCOSIDE,"TOBRAMYCIN, GENTAMICIN",NaN,aminoglycoside N-acetyltransferase AAC(2')-I(A...,-,Reference Gene Catalog,-
1,BAM16262.1,aac(2')-IIa,BAM16262.1,AB669090.1,AMINOGLYCOSIDE,KASUGAMYCIN,22660700,kasugamycin N-acetyltransferase AAC(2')-IIa,Enzymatic modification,"Reference Gene Catalog,ResFinder Database,Card...",ARO:3004628
2,APB03221.1,aac(2')-IIb,APB03221.1,KX531051.1,AMINOGLYCOSIDE,KASUGAMYCIN,27929110,kasugamycin N-acetyltransferase AAC(2')-IIb,antibiotic inactivation,"Reference Gene Catalog,Card Database",ARO:3003988
3,AAA03550.1,aac(2')-Ia,AAA03550.1,L06156.2,AMINOGLYCOSIDE,"DIBEKACIN, TOBRAMYCIN, GENTAMICIN, NETILMICIN,...","8407825,40178262",aminoglycoside N-acetyltransferase AAC(2')-Ia,Enzymatic modification,"Reference Gene Catalog,ResFinder Database,Card...",ARO:3002523
4,AAC44793.1,aac(2')-Ib,AAC44793.1,U41471.1,AMINOGLYCOSIDE,"TOBRAMYCIN, GENTAMICIN",8891143,aminoglycoside N-acetyltransferase AAC(2')-Ib,antibiotic inactivation,"Reference Gene Catalog,Card Database",ARO:3002524
...,...,...,...,...,...,...,...,...,...,...,...
18071,CAB13167.1_ARO:3003064,ykkD,CAB13167.1,AL009126.1,aminoglycoside antibiotic;phenicol antibiotic;...,,10735877,small multidrug resistance (SMR) antibiotic ef...,antibiotic efflux,Card Database,ARO:3003064
18072,QIU91361.1_ARO:3009096,YOC-1,QIU91361.1,CP050811.1,cephalosporin,,-,YOC beta-lactamase,antibiotic inactivation,Card Database,ARO:3009096
18073,AAC75271.1_ARO:3003952,YojI,AAC75271.1,U00096.3,peptide antibiotic,,15866933,ATP-binding cassette (ABC) antibiotic efflux pump,antibiotic efflux,Card Database,ARO:3003952
18074,ABA70720.1_ARO:3005035,YRC-1,ABA70720.1,DQ185144.1,cephalosporin;penicillin beta-lactam,,16553832,YRC beta-lactamase,antibiotic inactivation,Card Database,ARO:3005035
18075,WP_013992183.1_ARO:3007006,ZOG-1,WP_013992183.1,NG_057434.1,carbapenem,,-,ZOG beta-lactamase,antibiotic inactivation,Card Database,ARO:3007006

In [38]:
result_all.loc[result_all["ID"]=="BAB82500.1"]

,ID,gene_family,genbank_protein_accession,genbank_nucleotide_accession,class,subclass,pubmed_reference,product_name,Resistance Mechanism,Database,Notes
8007,BAB82500.1,tet(M),BAB82500.1,AB039845.1,TETRACYCLINE,TETRACYCLINE,19475445,tetracycline resistance ribosomal protection p...,antibiotic target protection,"Reference Gene Catalog,Card Database",ARO:3000186

In [39]:
result.loc[result["ID"]=="BAB82500.1"]

,ID,gene_family,genbank_protein_accession,genbank_nucleotide_accession,class,subclass,pubmed_reference,product_name,Resistance Mechanism,Database,Notes
8007,BAB82500.1,tet(M),BAB82500.1,AB039845.1,TETRACYCLINE,TETRACYCLINE,19475445,tetracycline resistance ribosomal protection p...,-,Reference Gene Catalog,-

In [40]:
result_all.iloc[0:2,:]

,ID,gene_family,genbank_protein_accession,genbank_nucleotide_accession,class,subclass,pubmed_reference,product_name,Resistance Mechanism,Database,Notes
0,CDI94966.1,aac(2')-I(A267),CDI94966.1,HG530068.1,AMINOGLYCOSIDE,"TOBRAMYCIN, GENTAMICIN",NaN,aminoglycoside N-acetyltransferase AAC(2')-I(A...,-,Reference Gene Catalog,-
1,BAM16262.1,aac(2')-IIa,BAM16262.1,AB669090.1,AMINOGLYCOSIDE,KASUGAMYCIN,22660700,kasugamycin N-acetyltransferase AAC(2')-IIa,Enzymatic modification,"Reference Gene Catalog,ResFinder Database,Card...",ARO:3004628

In [47]:
result_all.to_csv('genes_annotation_databases.csv', sep='\t', index=False)